project_id = "zdjlrxcsqicbumjgsern"

[functions.test-simple]
verify_jwt = false

[functions.analyze-openai]
verify_jwt = false

[functions.analyze-assistant]
verify_jwt = false

[functions.test-secrets]
verify_jwt = false

