// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdjlrxcsqicbumjgsern.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkamxyeGNzcWljYnVtamdzZXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzA3MTMsImV4cCI6MjA2ODg0NjcxM30.Ag6J9ZmPrEjBOnLTO3vQ8h6u4y_RKUZ_a8IBKBsdLfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});