// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback to existing values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 
  "https://zdjlrxcsqicbumjgsern.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkamxyeGNzcWljYnVtamdzZXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzA3MTMsImV4cCI6MjA2ODg0NjcxM30.Ag6J9ZmPrEjBOnLTO3vQ8h6u4y_RKUZ_a8IBKBsdLfk";

// Log configuration for debugging (only in development)
if (import.meta.env.DEV) {
  console.log('🔧 Decision Aid Supabase Config:', {
    url: SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    keyPrefix: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...'
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});